#define BAN_BANNED          "[CONTA] Você está banido, faça revisão no nosso discord."
#define BAN_WHOBANNED       "A conta %s foi banida pelo administrador %s, motivo: %s, em %s, o seu desbanimento estava agendado para %s. (GMT-03:00)"
#define BAN_MISTAKE         "Se você achasque isto é um erro, tire uma screenshot e faça revisão no nosso discord"
#define BAN_DCLINK          "discord.gg/URL"

#define REGISTRO_MSG       "Você registrou com sucesso a conta %s."

#define LOGIN_MSG1	">> Bem vindo novamente, {6B54B6}%s!"
#define LOGIN_MSG2	">> Seu nível admin é: %s."
#define LOGIN_MSG3	">> Seu último login foi em: %s."

#define ARENA_ENDED_MSG		">> A arena %s (ID: %d) acabou, a próxima é %s (ID: %d)."